### ISSUE TITLE
I need to message you about the CubeBots mod you did a little work on in 2013.

### ISSUE THREAD

**Issue by jadenquinn** [T145/actual-stellar-systems#1]
DM me on Discord or something - iRed#9321
I'm trying to track down the CubeBots mod for 1.6.2 and I saw your thread on MinecraftForums that basically said you made a stable version for 1.6.2, but said repo doesn't exist anymore but it was on T145, and I didn't have any way of messaging you on anything else, so here is this stupid hail mary of an issue.
Thank you.

**Comment by T145** [comment]
Hey! That's certainly a throw-back. IIRC I gave the project away to someone else, as it's not in my project archive.

If you're looking to make your own version it's very easy. Just copy ocelot and some Thaumcraft golem AI, make a cube entity with the texture of a stone slab, slap on a smiley face and you have a CubeBot.

**Comment by jadenquinn** [comment]
Lol I am not a dev. I'm not above paying someone to do it for me though. The best thing (for me) about the one for 1.5.2 was just how the AI was.. you know when you break the block a pig is gonna try to step on like 2-4 "steps" in the future? It just kind of jumps and spins in place, at least in that version. I love that and the CubeBot was even funnier when doing that, and it even does it on its own. Super funny. Added it to several packs myself.

**Comment by jadenquinn** [comment]
I am recovering my old NAS drives, on which the 1.6.2 version should be, so hopefully I can find it after that finishes. Do you remember who you gave the project to?

(Yes.. I literally just remembered this lol, my brain needs more dedotated wam and a PCIe SSD)
